#!/usr/bin/python
# -*- coding: utf-8 -*-
# kate: space-indent on; indent-width 4; mixedindent off; indent-mode python;

vim = [
    {'name':'common', 
    'mainpackage':True,
    'shortdesc':'Installs common package for the enhanced vi editor',
    'packages':['vim', 'vim-doc', 'vim-runtime'],
    },
    {'name':'tiny',
    'shortdesc':'Installs enhanced vi editor - compact version',
    'depends':['common'],
    'side-by-side':['basic', 'tiny', 'gnome', 'cream', 'gtk', 'nox', 'athena'],
    'packages':['vim-tiny'],
    },
    {'name':'basic',
    'shortdesc':'Installs enhanced vi editor - basic version',
    'depends':['common'],
    'side-by-side':['basic', 'tiny', 'gnome', 'cream', 'gtk', 'nox', 'athena'],
    'packages':[],
    },
    {'name':'gtk',
    'shortdesc':'Installs enhanced vi editor - compiled with the GTK2 GUI',
    'depends':['common'],
    'side-by-side':['basic', 'tiny', 'gnome', 'cream', 'gtk', 'nox', 'athena'],
    'packages':['vim-gtk'],
    },
    {'name':'gnome',
    'shortdesc':'Installs enhanced vi editor - compiled with a GNOME2 GUI',
    'depends':['common'],
    'side-by-side':['basic', 'tiny', 'gnome', 'cream', 'gtk', 'nox', 'athena'],
    'packages':['vim-gnome'],
    },
    {'name':'athena',
    'shortdesc':'Installs enhanced vi editor - compiled with an Athena GUI',
    'depends':['common'],
    'side-by-side':['basic', 'tiny', 'gnome', 'cream', 'gtk', 'nox', 'athena'],
    'packages':['vim-athena'],
    },
    {'name':'cream',
    'shortdesc':'Installs enhanced vi editor with VIM macros for beginners',
    'depends':[('gnome','gtk')],
    'side-by-side':['basic', 'tiny', 'gnome', 'cream', 'gtk', 'nox', 'athena'],
    'packages':['cream'],
    },
    {'name':'nox',
    'shortdesc':'Installs enhanced vi editor without X',
    'depends':['common'],
    'side-by-side':['basic', 'tiny', 'gnome', 'cream', 'gtk', 'nox', 'athena'],
    'packages':['vim-nox'],
    },
    {'name':'none', 'shortdesc':'Uninstalls the enhanced vi editor', 'packages':[] },
]
